spring.application.name=program
spring.datasource.url=jdbc:mysql://localhost:3306/third_program?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rahul123@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true